#!/bin/sh
# Creates .env on first use, with freshly generated values.
#
# The point is that `git clone && ./run.sh` works with no manual setup, and
# still without a single credential in the repository: the values below key
# hashes and HMACs inside a throwaway stack, they are generated per machine, and
# .env is gitignored.
#
# An existing .env is never overwritten - the Argon2 hashes of the seeded
# accounts are keyed by ARGON_SECRET, so rotating it silently invalidates every
# password already in the database.

set -e

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
ENV_FILE="$ROOT/.env"

# Appends any key that a newer version of this file introduced but an existing
# .env predates. Only ever adds - an existing value is left exactly as it is.
ensure_key() {
    grep -q "^$1=" "$ENV_FILE" 2>/dev/null && return 0
    printf '%s\n' "$2" >> "$ENV_FILE"
    echo " - added $1 to $ENV_FILE"
}

# The optional public-URL settings, which have no generated value: they name an
# ngrok domain and an account, and stay blank until someone fills them in.
ensure_public_keys() {
    if ! grep -q '^NGROK_DOMAIN=\|^NGROK_AUTHTOKEN=\|^GOOGLE_CLIENT_ID=' "$ENV_FILE" 2>/dev/null; then
        printf '\n%s\n' "# --- Public URL (optional; ./run.sh public=on) -------------------------------" >> "$ENV_FILE"
    fi
    ensure_key NGROK_DOMAIN     'NGROK_DOMAIN='
    ensure_key NGROK_AUTHTOKEN  'NGROK_AUTHTOKEN='
    ensure_key GOOGLE_CLIENT_ID 'GOOGLE_CLIENT_ID='
}

if [ -f "$ENV_FILE" ]; then
    ensure_public_keys
    exit 0
fi

# Prefers the kernel CSPRNG, falls back to openssl. Both are available on any
# machine that can run Docker.
random() {
    if [ -r /dev/urandom ]; then
        LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 48
    else
        openssl rand -base64 36 | tr -dc 'A-Za-z0-9' | head -c 48
    fi
}

echo "Generating $ENV_FILE (first run)..."

cat > "$ENV_FILE" << EOF
# Generated by scripts/prepare-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Gitignored. Delete this file and re-run to start from a clean slate - you must
# then also recreate the database volume, because the seeded password hashes are
# keyed by ARGON_SECRET:
#   docker compose down -v

APP_URL=http://172.19.0.9:3000
APP_WS_URL=ws://172.19.0.9:3000/ws

POSTGRES_USER=artra
POSTGRES_DB=artra
POSTGRES_PASSWORD=$(random)

SEED_STUDENT_EMAIL=student@artra.test
SEED_USER_PASSWORD=$(random)

ARGON_SECRET=$(random)
CODE_PEPPER=$(random)
PASSWORD_RESET_SECRET=$(random)
SIGNATURE_SECRET=$(random)
IP_SECRET=$(random)

EMAIL_FROM="Artra <no-reply@artra.test>"
EMAIL_REPLY_TO=support@artra.test

# --- Public URL (optional; ./run.sh public=on) -------------------------------
# Blank by default, and the suite does not need them: they only matter for the
# mode that serves the application over HTTPS on a public domain, which is what
# Google's sign-in button requires. See the README.
#
#   NGROK_DOMAIN     a reserved ngrok domain, no scheme
#   NGROK_AUTHTOKEN  from https://dashboard.ngrok.com/get-started/your-authtoken
#   GOOGLE_CLIENT_ID the OAuth client whose authorised origin is that domain
NGROK_DOMAIN=
NGROK_AUTHTOKEN=
GOOGLE_CLIENT_ID=
EOF

chmod 600 "$ENV_FILE"
echo " - wrote $ENV_FILE (mode 600, gitignored)"
