#!/bin/sh
# Creates .env on first use, with freshly generated values.
#
# The point is that `git clone && ./run.sh` works with no manual setup, and
# still without a single credential in the repository: the values below key
# hashes and HMACs inside a throwaway stack, they are generated per machine, and
# .env is gitignored.
#
# An existing .env is never overwritten - the Argon2 hashes of the seeded
# accounts are keyed by ARGON_SECRET, so rotating it silently invalidates every
# password already in the database.

set -e

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
ENV_FILE="$ROOT/.env"

if [ -f "$ENV_FILE" ]; then
    exit 0
fi

# Prefers the kernel CSPRNG, falls back to openssl. Both are available on any
# machine that can run Docker.
random() {
    if [ -r /dev/urandom ]; then
        LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 48
    else
        openssl rand -base64 36 | tr -dc 'A-Za-z0-9' | head -c 48
    fi
}

echo "Generating $ENV_FILE (first run)..."

cat > "$ENV_FILE" << EOF
# Generated by scripts/prepare-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Gitignored. Delete this file and re-run to start from a clean slate - you must
# then also recreate the database volume, because the seeded password hashes are
# keyed by ARGON_SECRET:
#   docker compose down -v

APP_URL=https://artra.test
APP_WS_URL=wss://artra.test/ws

POSTGRES_USER=artra
POSTGRES_DB=artra
POSTGRES_PASSWORD=$(random)

SEED_STUDENT_EMAIL=student@artra.test
SEED_USER_PASSWORD=$(random)

ARGON_SECRET=$(random)
CODE_PEPPER=$(random)
PASSWORD_RESET_SECRET=$(random)
SIGNATURE_SECRET=$(random)
IP_SECRET=$(random)

EMAIL_FROM="Artra <no-reply@artra.test>"
EMAIL_REPLY_TO=support@artra.test
EOF

chmod 600 "$ENV_FILE"
echo " - wrote $ENV_FILE (mode 600, gitignored)"
